/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Flaschenzug.glb --output src/components/Flaschenzug.jsx
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes } = useGLTF('/models/Flaschenzug.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Node1} />
    </group>
  )
}

useGLTF.preload('/models/Flaschenzug.glb')
export default Model
