/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Flaschenzug.glb --output src/components/Flaschenzug.jsx
*/

import { useMemo, useRef, useLayoutEffect } from 'react';
import { useGLTF } from '@react-three/drei'
import { Box3, Vector3 } from 'three';

export function Model(props) {
  const { nodes } = useGLTF('/models/Flaschenzug.glb')
  const centerRef = useRef();

  // useGLTF caches the parsed scene by URL, so every mount (card
  // thumbnail + full-screen viewer) shares the same node instances.
  // An Object3D can only have one parent, so rendering it directly in
  // two places at once steals it from whichever mounted first. Clone
  // per component instance instead.
  const clonedNode = useMemo(() => nodes.Node1.clone(), [nodes]);

  useLayoutEffect(() => {
    if (!centerRef.current) return;
    const center = new Box3().setFromObject(centerRef.current).getCenter(new Vector3());
    centerRef.current.position.set(-center.x, -center.y, -center.z);
  }, []);

  return (
    <group {...props} dispose={null}>
      <group ref={centerRef}>
        <primitive object={clonedNode} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Flaschenzug.glb')
export default Model
