/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 hacker-room-new.glb -T 
Files: hacker-room-new.glb [34.62MB] > /Users/hsuwinlat/Desktop/jsm pj/threejscc-portfolio/public/models/hacker-room-new-transformed.glb [2.56MB] (93%)
*/

import { useGLTF, useTexture } from '@react-three/drei';


export function HackerRoom(props) {
  const { nodes, materials } = useGLTF('/models/car.glb')

  return (
    <group {...props} dispose={null}>
      <group position={[-0.142, -57.17, 0]} rotation={[-Math.PI / 2, 0.005, 0]} scale={0.025}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 30.961, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_body01_0.geometry}
              material={materials.body01}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_body01_0_1.geometry}
              material={materials.body01}
            />
          </group>
          <group position={[0, 30.961, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.interior_intr01_0.geometry}
              material={materials.intr01}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.interior_intr01_0_1.geometry}
              material={materials.intr01}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.floor_floor01_0.geometry}
            material={materials.floor01}
            position={[0, 0, -0.468]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RearWheelR_rwheel01_0.geometry}
            material={materials.rwheel01}
            position={[-30.771, 14.214, -58.702]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FrontWheelR_frwheel01_0.geometry}
            material={materials.frwheel01}
            position={[-30.771, 14.214, 74.921]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FrontWheelL_frwheel01_0.geometry}
            material={materials.frwheel01}
            position={[30.771, 14.214, 74.921]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.roof_roof01_0.geometry}
            material={materials.roof01}
            position={[0, 30.961, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LightsL_lights01_0.geometry}
            material={materials.lights01}
            position={[19.977, 24.032, -1.928]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LightsR_lights01_0.geometry}
            material={materials.lights01}
            position={[-19.977, 24.032, -1.928]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RearWheelL_rwheel01_0.geometry}
            material={materials.rwheel01}
            position={[30.771, 14.214, -58.702]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.STwheel_stwheel01_0.geometry}
            material={materials.stwheel01}
            position={[13.084, 38.265, 13.093]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.instruments_instr01_0.geometry}
            material={materials.instr01}
            position={[0, 39.655, 23.615]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorL_body01_0.geometry}
            material={materials.body01}
            position={[26.019, 28.234, 5.554]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DoorR_body01_0.geometry}
            material={materials.body01}
            position={[-26.019, 28.234, 5.554]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IndoorL_intr01_0.geometry}
            material={materials.intr01}
            position={[24.65, 28.599, 6.949]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IndoorR_intr01_0.geometry}
            material={materials.intr01}
            position={[-24.651, 28.599, 6.949]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wingshild_Glass_0.geometry}
            material={materials.Glass}
            position={[0, 30.961, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.rearGlass_Glass_0.geometry}
            material={materials.Glass}
            position={[0, 30.961, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.instrGlass_InstrGlass_0.geometry}
            material={materials.InstrGlass}
            position={[0, 39.655, 23.615]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.StWGlass_StWGlass_0.geometry}
            material={materials.StWGlass}
            position={[13.084, 38.265, 13.093]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Buttons_ButtonGlass_0.geometry}
            material={materials.ButtonGlass}
            position={[0, 30.961, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BtakeLight_BRKGlass_0.geometry}
            material={materials.BRKGlass}
            position={[19.977, 24.032, -1.928]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.TurnLight_TRNGlass_0.geometry}
            material={materials.TRNGlass}
            position={[19.977, 24.032, -1.928]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.HeadLight_HDLight_0.geometry}
            material={materials.HDLight}
            position={[19.977, 24.032, -1.928]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object001_body01_0.geometry}
            material={materials.body01}
            position={[0, 30.961, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/car.glb');
export default HackerRoom;  
