/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useMemo, useRef, useLayoutEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { Box3, Vector3 } from 'three';

export function Hubwerkseinheit(props) {
  const { scene } = useGLTF('/models/Hubwerkseinheit.glb');
  const centerRef = useRef();

  // useGLTF caches the parsed scene by URL, so every mount (card
  // thumbnail + full-screen viewer) shares the same node instances.
  // An Object3D can only have one parent, so rendering it directly in
  // two places at once steals it from whichever mounted first. Clone
  // per component instance instead.
  const clonedScene = useMemo(() => {
    const clone = scene.clone();
    clone.traverse((obj) => {
      if (obj.isMesh) {
        obj.castShadow = true;
        obj.receiveShadow = true;
      }
    });
    return clone;
  }, [scene]);

  useLayoutEffect(() => {
    if (!centerRef.current) return;
    const center = new Box3().setFromObject(centerRef.current).getCenter(new Vector3());
    centerRef.current.position.set(-center.x, -center.y, -center.z);
  }, []);

  return (
    <group {...props} dispose={null}>
      <group ref={centerRef}>
        <primitive object={clonedScene} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Hubwerkseinheit.glb')
export default Hubwerkseinheit;
